title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
lang: fr
locale: fr_FR
baseurl: '/'

liquid:
  error_mode: strict
  strict_filters: true

twitter:
  username: coworkinglyon

facebook:
  page: Coworkinglyon
  app_id: 106737945179435

instagram:
  username: "atelierdesmedias_lyon"

#webmaster_verifications:
#  google: TODO
#  bing: TODO
#  facebook: TODO

exclude:
  - Makefile
  - Rakefile
  - sync.rb
  - events.rb
  - .github

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

collections:
  formulas:
    output: true
  coworkers:
    output: true
  events:
    output: true
  posts:
    output: true
    permalink: /:title/

pagination:
  enabled: true
  per_page: 8
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

postcss:
  cache: false
