title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
meta_robots: noindex
lang: fr
locale: fr_FR

liquid:
  error_mode: strict
  strict_filters: true

show_social_icons: true

twitter:
  username: coworkinglyon

facebook:
  page: Coworkinglyon

instagram:
  username: "atelierdesmedias_lyon"

exclude:
  - Makefile
  - Rakefile
  - sync.rb
  - .github

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  coworkers:
    output: true
