title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
base_url: "adm"

exclude:
  - Makefile

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  coworkers:
    output: true
