name: Build and deploy Jekyll site to GitHub Pages

on: push
#on:
#  push:
#    branches:
#      - main # or master before October 2020
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install gems
        run: bundle install
      - name: Generate the coworkers pages
        env:
          COWORKERS_URL: "https://intra.atelier-medias.org/xwiki/bin/get/XWiki/CoworkersService"
          COWORKERS_CODE: ${{ secrets.COWORKERS_CODE }}
        run: ruby sync.rb
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
